services: 
  node-app:                                                
    volumes: 
      - ./src:/app/src:ro              ### NOTE: here you can use (relative path)
    environment:
      - NODE_ENV=development