services: 
  node-app: 
    container_name: express-node-app-container              
    build: .                                                
    volumes: 
      - ./src:/app/src:ro              ### NOTE: here you can use (relative path)
    ports: 
      - "4000:4000"
    env_file: 
      - ./.env
    environment:
      - NODE_ENV=development